# Generated by Django 3.2.8 on 2021-11-02 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211102_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='isDelivery',
            new_name='isDelivered',
        ),
    ]
